export default [
  {
    id: 0,
    name: 'Hoddie',
    // image: require('./picture2.png'),
    image: 'https://4.imimg.com/data4/GH/SL/MY-9457126/12345-500x500.jpg',
    quantity: 5,
    price: 300,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['red', 'yellow', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 0,
  },
  {
    id: 1,
    name: 'Jacket',
    image:
      'https://www.expocafeperu.com/w/2020/04/winter-coat-men-sale-canada-mens-nike-jacket-designer-clearance-trench-slim-fit-wool-uk-warm-coats-4xl-fashion-2020-wear-superdry-cheap-olukai-ohana-women-yoga.jpg',
    quantity: 10,
    price: 400,
    add_to_cart: true,
    product_size: ['M', 'L', 'XL'],
    product_color: ['blue', 'green', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 0,
  },
  {
    id: 2,
    name: 'Hoddie',
    image:
      'https://ae01.alicdn.com/kf/H5bbdf4407ec74cee88d9d709707ece5b7/Hoodies-Men-2020-Spring-Fashion-Tracksuit-Sweatshirt-Men-s-Winter-Long-Sleeves-Pullover-Hoodie-Sports-Sweatshirts.jpg',
    quantity: 5,
    price: 350,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['red', 'yellow', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 0,
  },
  {
    id: 3,
    name: 'T-shirt',
    image:
      'https://images-na.ssl-images-amazon.com/images/I/513favBlpgL._UX569_.jpg',
    quantity: 3,
    price: 200,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['red', 'yellow', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 0,
  },
  {
    id: 4,
    name: 'jacket',
    image:
      'https://images-na.ssl-images-amazon.com/images/I/61qGsFu6mNL._UL1024_.jpg',
    quantity: 3,
    price: 300,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['red', 'yellow', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 0,
  },
  {
    id: 5,
    name: 'T-shirt',
    image:
      'https://www.rollingstone.com/wp-content/uploads/2020/05/Screen-Shot-2020-05-21-at-12.34.06.png?w=856',
    quantity: 3,
    price: 150,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['red', 'yellow', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 0,
  },
  {
    id: 6,
    name: 'shose',
    image:
      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/192790/02/sv01/fnd/IND/fmt/png/Flyer-Runner-Engineered-Knit-SoftFoam+-Men's-Running-Shoes",
    quantity: 3,
    price: 600,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['red', 'yellow', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 0,
  },
  {
    id: 7,
    name: 'socks',
    image:
      'https://www.dim.com/dw/image/v2/AARR_PRD/on/demandware.static/-/Sites-dim-master/default/dw00b2106a/D025WM2-0HY_01.jpg?sw=600&sh=600&sm=fit',
    quantity: 3,
    price: 20,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['red', 'yellow', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 0,
  },
  {
    id: 8,
    name: 'Pants',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqWAJDivZQul1C8WjXVOPpB8CyDNz4-12qHA&usqp=CAU',
    quantity: 3,
    price: 150,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['red', 'yellow', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 0,
  },
  {
    id: 9,
    name: 'Pants',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqXTDRzvA_zXlOkDHKHvqPsOTW86JCYats7A&usqp=CAU',
    quantity: 3,
    price: 250,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['red', 'yellow', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 0,
  },
  {
    id: 10,
    name: 'shose',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_xdQ5dDjZ7Gq7FS2Qu1oe1Oe_PNTLSEYfpA&usqp=CAU',
    quantity: 10,
    price: 400,
    add_to_cart: true,
    product_size: ['M', 'L', 'XL'],
    product_color: ['blue', 'green', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 0,
  },
  {
    id: 11,
    name: 'shose',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9mRDvpvI2DNo0QkciWsPAUG7yfdlFhTEMKQ&usqp=CAU',
    quantity: 10,
    price: 320,
    add_to_cart: true,
    product_size: ['M', 'L', 'XL'],
    product_color: ['blue', 'green', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 0,
  },
  {
    id: 12,
    name: 'socks',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0SQC7w3HFpfCZbexRPWhVywZ5Ya5WzFhxsg&usqp=CAU',
    quantity: 10,
    price: 15,
    add_to_cart: true,
    product_size: ['M', 'L', 'XL'],
    product_color: ['blue', 'green', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 0,
  },
  {
    id: 12,
    name: 'T-shirt',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxDFI6zsNFgVfiIKaL5eHUEroY6m2dAbc97Q&usqp=CAU',
    quantity: 10,
    price: 210,
    add_to_cart: true,
    product_size: ['M', 'L', 'XL'],
    product_color: ['blue', 'green', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 0,
  },
  {
    id: 12,
    name: 'T-shirt',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQ3PNF6omti_izWCQlgjiPUtIurAvS__8Ipw&usqp=CAU',
    quantity: 10,
    price: 400,
    add_to_cart: true,
    product_size: ['M', 'L', 'XL'],
    product_color: ['blue', 'green', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 0,
  },
];
